language: go
go:
  - 1.x
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - liblvm2-dev
      - libdevmapper-dev
before_install:
  - sudo apt-get update
  - go get -u github.com/nak3/go-lvm

script:
  - go run cmd/example.go
